# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NodeJS API build Pipeline

on:
  workflow_dispatch:  # This allows manual execution

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Set Jest Permissions
        run: chmod +x ./node_modules/.bin/jest

      - name: Run Tests
        run: npx jest --verbose

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test # Runs only if "test" job succeeds
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Application Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-nodejs-api:latest .

  publish:
    name: Publish to GHCR
    runs-on: ubuntu-latest
    needs: build  # Runs only if "build" job succeeds
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image to GHCR
        run: |
          docker tag ghcr.io/${{ github.repository }}/my-nodejs-api:latest ghcr.io/${{ github.repository }}/my-nodejs-api:${{ github.run_number }}
          docker push ghcr.io/${{ github.repository }}/my-nodejs-api:latest
          docker push ghcr.io/${{ github.repository }}/my-nodejs-api:${{ github.run_number }}


